# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ccc9b472a1978f8cc5d5daa5b07cbdef57f3e4cb81209fc6b81f71ea2673cd21f02ab3b79e1a4a08513c607505356ab1d5f3b10317f24c81397425b831c491

test:
  secret_key_base: 9c8318ba58fd3c09cc05be7a66c52db526aa0f2bbd40dd1a050f0911ab8e487b650885d59493617bac6f7ac813f8e99720846a6a5256d877d447b9aba90a64b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
